javac Aquarium.java;
javac Coin.java;
javac Controller.java;
javac Drawable.java;
javac DroppableItem.java;
#~ javac DroppableItemTest.java;
javac Fish.java;
javac FishFood.java;
#~ javac FishTest.java;
javac Guppy.java;
#~ javac GuppyTest.java;
javac LinkedList.java;
#~ javac LinkedListTest.java;
javac Main.java;
javac MovingObject.java;
javac Piranha.java;
#~ javac PiranhaTest.java;
javac Player.java;
#~ javac PlayerTest.java;
javac Position.java;
#~ javac PositionTest.java;
javac Snail.java;
